function setOutputColor() end
function getMaxEnergy() end
function decrementOutputColor() end
function incrementInputColor() end
function setRedstoneMode() end
function hasStrictInput() end
function setStockControl() end
function getOwnerName() end
function incrementMode() end
function setAutoMode() end
function getInstalledUpgrades() end
function clearInputColor() end
function getDirection() end
function hasRecipe() end
function encodeFormula() end
function getStockControl() end
function getSupportedModes() end
function getInputColor() end
function getEnergyItem() end
function setEjecting() end
function getAutoMode() end
function craftSingleItem() end
function setInputColor() end
function getConfigurableTypes() end
function getRedstoneMode() end
function getSlots() end
function setMode() end
function getSecurityMode() end
function decrementMode() end
function canEject() end
function getCraftingOutputSlots() end
function hasValidFormula() end
function getEnergyNeeded() end
function getCraftingInputSlot() end
function isEjecting() end
function getTicksRequired() end
function fillOrEmptyGrid() end
function getExcessRemainingItems() end
function getMode() end
function getEnergyFilledPercentage() end
function getRecipeProgress() end
function getCraftingOutputSlot() end
function getComparatorLevel() end
function clearOutputColor() end
function getFormulaItem() end
function getItemInSlot() end
function getOwnerUUID() end
function craftAvailableItems() end
function incrementOutputColor() end
function decrementInputColor() end
function getOutputColor() end
function getSupportedUpgrades() end
function setStrictInput() end
function getEnergy() end



